apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvops-bloggers-deploy  # Name of the deployment
spec:
  replicas: 2  # Always maintain 2 pods
  selector:
    matchLabels:
      app: dvops-bloggers
  template:
    metadata:
      labels:
        app: dvops-bloggers
      annotations:
        build-number: "{{BUILD_NUMBER}}"  # Forces a rollout when BUILD_NUMBER changes
    spec:
      containers:
        - name: dvops-bloggers
          image: dvops-bloggers-app:{{BUILD_NUMBER}}  # Docker image with Jenkins BUILD_NUMBER
          imagePullPolicy: IfNotPresent  # Use local Minikube image if available
          ports:
            - containerPort: 5050