apiVersion: v1
kind: Service
metadata:
  name: dvops-bloggers-service-azure  # Azure-specific service name
spec:
  type: LoadBalancer  # Azure will provision a public IP
  selector:
    app: dvops-bloggers-azure
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 5050  # Container port
